# Generated by Django 5.0.4 on 2024-05-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
